#!/usr/bin/with-contenv bash

cd /config || exit

exec \
	s6-setuidgid abc python /app/hydra/nzbhydra.py \
	--nobrowser --config /config/settings.cfg \
	--database /config/nzbhydra.db \
    --logfile /config/nzbhydra.log