#!/usr/bin/with-contenv bash

# unset special env variable that causes crashes
unset HOST_OS

# cd into dir, if error we just exit
cd /app/hydra2 || exit

exec \
	s6-setuidgid abc /app/hydra2/nzbhydra2wrapper.py \
	--nobrowser --datafolder /config